info:
  app:
    name: fitnessConsultation
    version: '0.1'
    grailsVersion: 6.0.0
grails:
  views:
    default:
      codec: html
  gorm:
    reactor:
      events: false
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
dataSource:
  dbCreate: create-drop
  url: jdbc:mysql://localhost/asp
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: '12345678'
  pooled: true
  jmxExport: true
  logSql: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
